### ISSUE TITLE
AttributeError(s) in Gedit 3.12.1

### ISSUE THREAD

**Issue by fedelibre** [bndn/gedit-sessionsaver#5]
I read that this plugin is for Gnome 3.0-3.8. I'm on debian testing (currently gnome 3.8), but Gedit is version 3.12.1.
I can activate the plugin, but when I launch Gedit I'm getting the following error:

```
$ gedit
Traceback (most recent call last):
  File "/home/fede/.local/share/gedit/plugins/sessionsaver/__init__.py", line 65, in do_activate
    self._insert_menu()
  File "/home/fede/.local/share/gedit/plugins/sessionsaver/__init__.py", line 74, in _insert_menu
    ui_manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
Traceback (most recent call last):
  File "/home/fede/.local/share/gedit/plugins/sessionsaver/__init__.py", line 71, in do_update_state
    self._action_group.get_action("FileSessionSave").set_sensitive(self.window.get_active_document() != None)
AttributeError: 'SessionSaverPlugin' object has no attribute '_action_group'
Traceback (most recent call last):
  File "/home/fede/.local/share/gedit/plugins/sessionsaver/__init__.py", line 71, in do_update_state
    self._action_group.get_action("FileSessionSave").set_sensitive(self.window.get_active_document() != None)
AttributeError: 'SessionSaverPlugin' object has no attribute '_action_group'
Traceback (most recent call last):
  File "/home/fede/.local/share/gedit/plugins/sessionsaver/__init__.py", line 71, in do_update_state
    self._action_group.get_action("FileSessionSave").set_sensitive(self.window.get_active_document() != None)
AttributeError: 'SessionSaverPlugin' object has no attribute '_action_group'
Traceback (most recent call last):
  File "/home/fede/.local/share/gedit/plugins/sessionsaver/__init__.py", line 68, in do_deactivate
    self._remove_menu()
  File "/home/fede/.local/share/gedit/plugins/sessionsaver/__init__.py", line 97, in _remove_menu
    ui_manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
```

**Comment by denpanosekai** [comment]
Same here. Using gedit 3.10.4
